<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #18181b; background: #fff; }

  .header { background: #7c3aed; color: #fff; padding: 24px 32px; }
  .header h1 { font-size: 22px; font-weight: bold; letter-spacing: -0.5px; }
  .header p  { font-size: 12px; opacity: 0.85; margin-top: 4px; }

  .meta { padding: 20px 32px; background: #f4f4f5; border-bottom: 1px solid #e4e4e7; }
  .meta table { width: 100%; }
  .meta td { padding: 3px 0; font-size: 11px; color: #52525b; }
  .meta td:first-child { font-weight: bold; color: #18181b; width: 140px; }

  .score-section { text-align: center; padding: 24px 32px; border-bottom: 1px solid #e4e4e7; }
  .score-circle { display: inline-block; width: 80px; height: 80px; border-radius: 50%; line-height: 80px; text-align: center; font-size: 32px; font-weight: bold; color: #fff; margin-bottom: 8px; }
  .score-good   { background: #16a34a; }
  .score-ok     { background: #ca8a04; }
  .score-bad    { background: #dc2626; }
  .score-label  { font-size: 13px; color: #52525b; }

  .section { padding: 20px 32px; border-bottom: 1px solid #e4e4e7; }
  .section h2 { font-size: 14px; font-weight: bold; margin-bottom: 10px; color: #3f3f46; border-left: 3px solid #7c3aed; padding-left: 8px; }

  .module-row { display: flex; justify-content: space-between; align-items: center; padding: 6px 0; border-bottom: 1px solid #f4f4f5; }
  .module-name { font-size: 11px; color: #3f3f46; }
  .badge { font-size: 10px; font-weight: bold; padding: 2px 8px; border-radius: 10px; }
  .badge-ok    { background: #dcfce7; color: #15803d; }
  .badge-warn  { background: #fef9c3; color: #a16207; }
  .badge-error { background: #fee2e2; color: #b91c1c; }

  .deductions { padding: 20px 32px; border-bottom: 1px solid #e4e4e7; }
  .deductions h2 { font-size: 14px; font-weight: bold; margin-bottom: 10px; color: #3f3f46; border-left: 3px solid #dc2626; padding-left: 8px; }
  .deduction-item { font-size: 11px; color: #52525b; padding: 3px 0; }
  .deduction-item::before { content: "• "; color: #dc2626; }

  .footer { padding: 16px 32px; background: #f4f4f5; }
  .footer p { font-size: 10px; color: #a1a1aa; }
  .footer a { color: #7c3aed; text-decoration: none; }

  .no-issues { font-size: 11px; color: #16a34a; font-style: italic; }
</style>
</head>
<body>

<div class="header">
  <h1>4uTest — Audit Report</h1>
  <p>Automated website health scan</p>
</div>

<div class="meta">
  <table>
    <tr><td>Scan Name</td><td>{{ $scan->name }}</td></tr>
    <tr><td>Site URL</td><td>{{ $scan->site_url }}</td></tr>
    <tr><td>Scan Date</td><td>{{ now()->format('d M Y, H:i') }} UTC</td></tr>
    <tr><td>Full Report</td><td>{{ $reportUrl }}</td></tr>
  </table>
</div>

<div class="score-section">
  @php
    $scoreClass = $score >= 70 ? 'score-good' : ($score >= 40 ? 'score-ok' : 'score-bad');
    $scoreLabel = $score >= 70 ? 'Good' : ($score >= 40 ? 'Needs Improvement' : 'Critical Issues');
  @endphp
  <div class="score-circle {{ $scoreClass }}">{{ $score ?? '?' }}</div>
  <div class="score-label">Health Score &mdash; {{ $scoreLabel }}</div>
</div>

<div class="section">
  <h2>Module Results</h2>
  @php
    $modules = [
      'SEO & Schema'         => $report->seo_schema_result,
      'Security'             => $report->security_result,
      'E-commerce Catalog'   => $report->catalog_result,
      'Marketing Tracking'   => $report->tracking_result,
      'Broken Resources'     => $report->broken_resources_result,
      'Performance'          => $report->performance_result,
      'Accessibility (WCAG)' => $report->accessibility_result,
    ];
  @endphp
  @foreach($modules as $label => $raw)
    @php
      $data   = $raw ? json_decode($raw, true) : null;
      $status = $data['status'] ?? 'pending';
      $badge  = $status === 'ok' ? 'badge-ok' : ($status === 'error' ? 'badge-error' : 'badge-warn');
      $text   = $status === 'ok' ? 'Completed' : ($status === 'error' ? 'Error' : 'Pending');
    @endphp
    <div class="module-row">
      <span class="module-name">{{ $label }}</span>
      <span class="badge {{ $badge }}">{{ $text }}</span>
    </div>
  @endforeach
</div>

@if(!empty($deductions))
<div class="deductions">
  <h2>Score Deductions</h2>
  @foreach($deductions as $d)
    <div class="deduction-item">{{ $d }}</div>
  @endforeach
</div>
@else
<div class="deductions">
  <h2>Score Deductions</h2>
  <p class="no-issues">No issues found — perfect score!</p>
</div>
@endif

<div class="footer">
  <p>Generated by <a href="https://4utest.io">4uTest</a> &mdash; Automated website auditing &mdash; {{ now()->format('Y') }}</p>
  <p style="margin-top:4px;">View the full interactive report at: <a href="{{ $reportUrl }}">{{ $reportUrl }}</a></p>
</div>

</body>
</html>
